---
controller:
  controller_ip: '10.52.3.142'
  controller_port: '50051'
workers:
  w1_ip: '129.114.108.158'
  w1_name: 'w1'
  w1_username: 'cc'
  w2_ip: '129.114.108.160'
  w2_name: 'w2'
  w2_username: 'cc'
  w3_ip: '129.114.108.232'
  w3_name: 'w3'
  w3_username: 'cc'
  w4_ip: '129.114.108.186'
  w4_name: 'w4'
  w4_username: 'cc'
  w5_ip: '129.114.109.213'
  w5_name: 'w5'
  w5_username: 'cc'
  w6_ip: '129.114.108.193'
  w6_name: 'w6'
  w6_username: 'cc'
  w7_ip: '129.114.108.59'
  w7_name: 'w7'
  w7_username: 'cc'
  w8_ip: '129.114.109.153'
  w8_name: 'w8'
  w8_username: 'cc'
