ssh cc@in1 "cd daemon && bash stop_daemons_new.sh"
ssh cc@in2 "cd daemon && bash stop_daemons_new.sh"
ssh cc@in3 "cd daemon && bash stop_daemons_new.sh"
ssh cc@in4 "cd daemon && bash stop_daemons_new.sh"
ssh cc@in9 "cd daemon && bash stop_daemons_new.sh"
ssh cc@in6 "cd daemon && bash stop_daemons_new.sh"
ssh cc@in7 "cd daemon && bash stop_daemons_new.sh"
ssh cc@in8 "cd daemon && bash stop_daemons_new.sh"

# ssh cc@in1 "cd daemon && bash stop_daemons.sh"
# ssh cc@in2 "cd daemon && bash stop_daemons.sh"
# ssh cc@in3 "cd daemon && bash stop_daemons.sh"
# ssh cc@in4 "cd daemon && bash stop_daemons.sh"
# ssh cc@in9 "cd daemon && bash stop_daemons.sh"
# ssh cc@in6 "cd daemon && bash stop_daemons.sh"
# ssh cc@in7 "cd daemon && bash stop_daemons.sh"
# ssh cc@in8 "cd daemon && bash stop_daemons.sh"
